### ISSUE TITLE
Give visibility to resources present in a Pulumi organization

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-cloud-requests#37] opened 2022-01-26 23:16 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

A Pulumi organization main page shows a graph over time as an indicative measure of how many resources are present in the said organization. However, the resource count is global and there's no direct way to get the resource count via an API. Furthermore, there's no way to have detailed information on the resource types and attributes.

While it's possible to iterate through all the projects, stack and resource count for each stack, this is an inefficient method of extracting this information. For this to work *correctly*, the user making the calls need to have visibility on all projects and all stacks with this organization, otherwise the count may be missing some resources.

## Feature details

1. It would be great to provide customers with better resource visibility via a single API endpoint where they could easily collect the current resource count and for each resource present in the code some detailed information such as `org`, `project`, `stack`, `creation date/time`, `resource type`.

2. Since an organization dashboard already displays a resource count via a graph, it it would be great to document the following URL `https://api.pulumi.com/api/orgs/<org_name>/resources/summary?lookbackDays=365&granularity=daily` in our [Service REST API](https://www.pulumi.com/docs/reference/service-rest-api/).

**Comment by EvanBoyle** [comment] 2022-01-26 23:26
@aureq is this a dupe of https://github.com/pulumi/service-requests/issues/24?

**Comment by aureq** [comment] 2022-01-27 00:06
@EvanBoyle I think they are closely related but not dupes. #24 asks for a search capability to a given resource type, where this one is about enumerating all resources at once for a given org.

**Comment by susanev** [comment] 2022-01-27 00:49
@aureq i have some early concepts of what browsing and filtering might look like for the set of all resources across an org. im gonna be scheduling a zoom with a small group of folks to share and get feedback. would you be up for being included in that?

**Comment by aureq** [comment] 2022-01-27 00:54
please please please, pretty please yes ! 🙏 @susanev

**Comment by dixler** [comment] 2022-07-13 12:29
This looks like my hackathon project.

**Comment by EvanBoyle** [comment] 2023-04-26 13:53
Resource search shipped last week. Give it a try and let us know what you think! This includes an API that you can use to enumerate all resources as well as the ability to export all resources to a CSV.

- [Launch blog](https://www.pulumi.com/blog/pulumi-insights/)
- [Documentation](https://www.pulumi.com/docs/intro/insights/search/)

**Closed by EvanBoyle** 2023-04-26 13:53 UTC
Labels: kind/enhancement, impact/usability, resolution/fixed
