### ISSUE TITLE
when a stack creator transfers a stack they no longer have stack creator

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-cloud-requests#184] opened 2023-02-18 21:05 UTC
when a stack creator transfers a stack they no longer have stack creator

repro steps
1. create a stack
2. notice the stack creator badge on the access page of the stacks settings
3. transfer that stack to an org
4. notice the stack creator badge is now gone

i only tested this by transferring to an org on team in which i was an org member not an org admin. i still had stack admin access but the creator badge was gone. have not tried to enterprise with role based access control yet
i think this removes a few permissions, but haven't fully tested yet, will a bit later today

**Comment by susanev** [comment] 2023-02-18 21:05
i found this in relation to this [slack community thread](https://pulumi-community.slack.com/archives/C84L4E3N1/p1676667115065939) where this person could no longer rename the stack after transferring

**Comment by kimberleyamackenzie** [comment] 2024-01-03 22:30
Brought this to the team, and we decided it is intentional behavior - @komalali specifically pointed out that `GitHub does the same thing when you transfer a repo, you no longer have admin access to the repo in the new org.`.  Closing this as by design - and it looks like the original item that brought this up has been fixed, so we should be good to go here.

**Closed by kimberleyamackenzie** 2024-01-03 22:30 UTC
Labels: kind/bug, resolution/by-design
